import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { QueryProvider } from "@/providers/query-provider";
import { CentralNotifier } from "@/components/ui/notifier";
import { ThemeSynchronizer } from "@/components/theme/theme-synchronizer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} font-sans h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const stored = localStorage.getItem("the-commons-ui-store");
                if (stored) {
                  const parsed = JSON.parse(stored);
                  const theme = parsed?.state?.themePalette || "paper";
                  const font = parsed?.state?.readingFont || "sans";
                  document.documentElement.setAttribute("data-theme", theme);
                  document.documentElement.setAttribute("data-reading-font", font);
                  if (theme === "midnight") {
                    document.documentElement.classList.add("dark");
                  }
                } else {
                  document.documentElement.setAttribute("data-theme", "paper");
                  document.documentElement.setAttribute("data-reading-font", "sans");
                }
              } catch (e) {}
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <ThemeSynchronizer />
          {children}
          <CentralNotifier />
        </QueryProvider>
      </body>
    </html>
  );
}
