-- Migration: 20261004000000_migrate_profiles_and_entities_to_integer_id.sql
-- Description: Comprehensive migration to integer primary keys (bigint generated by default as identity)
-- for profiles, allowed_members, diaries, diary_entries, goals, tasks, user_items, and document junctions.
-- Preserves auth.users foreign key mapping via `profiles.auth_user_id (uuid unique)`.

-- ==============================================================================
-- 1. DROP EXISTING DEPENDENT OBJECTS (CLEAN REBUILD FOR NUMERIC IDENTIFIERS)
-- ==============================================================================

-- Drop triggers
drop trigger if exists on_auth_user_created on auth.users;
drop trigger if exists on_profiles_updated on public.profiles;
drop trigger if exists on_user_items_updated on public.user_items;
drop trigger if exists on_diaries_updated on public.diaries;
drop trigger if exists on_diary_entries_updated on public.diary_entries;
drop trigger if exists set_goals_updated_at on public.goals;
drop trigger if exists set_tasks_updated_at on public.tasks;
drop trigger if exists on_tag_categories_updated on public.tag_categories;
drop trigger if exists on_tags_updated on public.tags;

-- Drop tables in dependency order
drop table if exists public.task_tags cascade;
drop table if exists public.tasks cascade;
drop table if exists public.goal_tags cascade;
drop table if exists public.goals cascade;
drop table if exists public.diary_entry_tags cascade;
drop table if exists public.document_tags cascade;
drop table if exists public.tags cascade;
drop table if exists public.tag_categories cascade;
drop table if exists public.diary_entries cascade;
drop table if exists public.diaries cascade;
drop table if exists public.user_items cascade;
drop table if exists public.allowed_members cascade;
drop table if exists public.profiles cascade;

-- ==============================================================================
-- 2. CREATE SCHEMAS WITH INTEGER / BIGINT IDENTIFIERS
-- ==============================================================================

-- 2.1 Profiles Table (Integer ID PK, auth_user_id FK to auth.users)
create table public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  username text unique,
  avatar_url text,
  bio text,
  role text not null default 'member' check (role in ('admin', 'member', 'guest')),
  sort_preferences jsonb not null default jsonb_build_object(
    'default_sort_by', 'created_at',
    'default_sort_order', 'desc',
    'filter_favorites_first', true
  ),
  email_preferences jsonb not null default jsonb_build_object(
    'marketing', false,
    'transactional', true,
    'newsletter', true,
    'product_updates', true,
    'digest_frequency', 'weekly'
  ),
  display_settings jsonb not null default jsonb_build_object(
    'theme', 'system',
    'density', 'comfortable',
    'view_mode', 'grid'
  ),
  metadata jsonb not null default jsonb_build_object(
    'residence', 'Archival Broadside',
    'clearance_title', 'Level II Scribe',
    'ritual_streak_days', 0,
    'unlocked_stamps', jsonb_build_array('founding_scribe')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2.2 Allowed Members Table (Integer ID PK)
create table public.allowed_members (
  id bigint generated by default as identity primary key,
  email text not null unique,
  added_by bigint references public.profiles(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'suspended', 'revoked')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2.3 User Items Table (Integer ID PK, Integer user_id FK)
create table public.user_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  category text,
  status text not null default 'active' check (status in ('active', 'archived', 'draft')),
  sort_order integer not null default 0,
  is_pinned boolean not null default false,
  is_favorite boolean not null default false,
  tags text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2.4 Diaries Table (Integer ID PK, Integer user_id FK)
create table public.diaries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  theme text not null default 'vintage' check (theme in ('vintage', 'classic', 'modern')),
  cover_color text default '#8C3A27',
  is_favorite boolean not null default false,
  is_archived boolean not null default false,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2.5 Diary Entries Table (Integer ID PK, Integer diary_id & user_id FKs)
create table public.diary_entries (
  id bigint generated by default as identity primary key,
  diary_id bigint not null references public.diaries(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  page_number integer not null default 1,
  entry_date date not null default current_date,
  date_str text not null,
  day_of_week text not null,
  year_str text not null,
  title text not null default '',
  description text not null default '',
  gratitude text[] not null default array['', '', '']::text[],
  energy_level integer not null default 3 check (energy_level between 1 and 5),
  start_time text default '09:00',
  end_time text default '17:00',
  mood text not null default '🌿 Calm',
  weather text not null default 'sunny',
  is_hearted boolean not null default false,
  tags text[] not null default '{}',
  word_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint unique_diary_page_number unique (diary_id, page_number)
);

-- 2.6 Tag Categories & Tags Tables (Integer ID PKs, Integer user_id FK)
create table public.tag_categories (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  feature text not null default 'general',
  name varchar(50) not null,
  color varchar(7) not null default '#6B7280',
  display_order integer not null default 0,
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint uq_user_feature_category_name unique (user_id, feature, name)
);

create table public.tags (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.tag_categories(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  name varchar(50) not null,
  color varchar(7) default null,
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint uq_user_tag_in_category unique (category_id, name)
);

-- 2.7 Junctions: Diary Entry Tags & Document Tags (Integer IDs)
create table public.diary_entry_tags (
  entry_id bigint not null references public.diary_entries(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),

  primary key (entry_id, tag_id)
);

create table public.document_tags (
  document_id bigint not null,
  tag_id bigint not null references public.tags(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),

  primary key (document_id, tag_id)
);

-- 2.8 Goals & Goal Tags Tables (Integer ID PKs, Integer parent_id & user_id FKs)
create table public.goals (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  parent_id bigint references public.goals(id) on delete cascade,
  
  title varchar(255) not null,
  description text,
  type public.goal_type not null default 'daily',
  status public.goal_status not null default 'draft',
  priority public.goal_priority not null default 'normal',
  
  start_date timestamptz,
  due_date timestamptz,
  achieved_at timestamptz,
  cancelled_at timestamptz,
  cancel_reason text,
  
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.goal_tags (
  goal_id bigint not null references public.goals(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),

  primary key (goal_id, tag_id)
);

-- 2.9 Tasks & Task Tags Tables (Integer ID PKs, Integer parent_id & user_id FKs)
create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  parent_id bigint references public.tasks(id) on delete cascade,
  
  title varchar(255) not null,
  description text,
  status public.task_status not null default 'todo',
  priority public.task_priority not null default 'normal',
  
  scheduled_date date,
  due_date timestamptz,
  completed_at timestamptz,
  
  time_estimate_minutes integer check (time_estimate_minutes is null or time_estimate_minutes >= 0),
  actual_minutes integer check (actual_minutes is null or actual_minutes >= 0),
  sort_order integer not null default 0,
  
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.task_tags (
  task_id bigint not null references public.tasks(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),

  primary key (task_id, tag_id)
);

-- ==============================================================================
-- 3. INDEXES
-- ==============================================================================
create index idx_profiles_auth_user_id on public.profiles(auth_user_id);
create index idx_profiles_email on public.profiles(email);
create index idx_profiles_role on public.profiles(role);

create index idx_allowed_members_email on public.allowed_members(email);
create index idx_allowed_members_status on public.allowed_members(status);

create index idx_user_items_user_sort_order on public.user_items(user_id, sort_order asc);
create index idx_user_items_user_created_at on public.user_items(user_id, is_pinned desc, created_at desc);
create index idx_user_items_user_status on public.user_items(user_id, status);

create index idx_diaries_user_sort on public.diaries(user_id, is_favorite desc, sort_order asc, created_at desc);
create index idx_diaries_user_archived on public.diaries(user_id, is_archived);

create index idx_diary_entries_diary_page on public.diary_entries(diary_id, page_number desc);
create index idx_diary_entries_user_date on public.diary_entries(user_id, entry_date desc);
create index idx_diary_entries_user_hearted on public.diary_entries(user_id, is_hearted) where is_hearted = true;
create index idx_diary_entries_tags on public.diary_entries using gin (tags);
create index idx_diary_entries_mood on public.diary_entries(user_id, mood);

create index idx_tag_categories_user_feature on public.tag_categories(user_id, feature, display_order asc, name asc);
create index idx_tags_category_id on public.tags(category_id);
create index idx_tags_user_id on public.tags(user_id, name asc);

create index idx_diary_entry_tags_tag_id on public.diary_entry_tags(tag_id, user_id);
create index idx_diary_entry_tags_entry_id on public.diary_entry_tags(entry_id, user_id);
create index idx_document_tags_tag_id on public.document_tags(tag_id, user_id);
create index idx_document_tags_document_id on public.document_tags(document_id, user_id);

create index idx_goals_user_id on public.goals(user_id);
create index idx_goals_parent_id on public.goals(parent_id);
create index idx_goals_status_due on public.goals(status, due_date);
create index idx_goals_priority on public.goals(user_id, priority);
create index idx_goals_type on public.goals(user_id, type);
create index idx_goals_created_at on public.goals(user_id, created_at desc);
create index idx_goal_tags_tag_id on public.goal_tags(tag_id, user_id);
create index idx_goal_tags_user_id on public.goal_tags(user_id);

create index idx_tasks_user_id on public.tasks(user_id);
create index idx_tasks_parent_id on public.tasks(parent_id);
create index idx_tasks_user_scheduled on public.tasks(user_id, scheduled_date);
create index idx_tasks_user_status on public.tasks(user_id, status);
create index idx_tasks_user_priority on public.tasks(user_id, priority);
create index idx_tasks_created_at on public.tasks(user_id, created_at desc);
create index idx_task_tags_tag_id on public.task_tags(tag_id, user_id);
create index idx_task_tags_user_id on public.task_tags(user_id);

-- ==============================================================================
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
alter table public.profiles enable row level security;
alter table public.allowed_members enable row level security;
alter table public.user_items enable row level security;
alter table public.diaries enable row level security;
alter table public.diary_entries enable row level security;
alter table public.tag_categories enable row level security;
alter table public.tags enable row level security;
alter table public.diary_entry_tags enable row level security;
alter table public.document_tags enable row level security;
alter table public.goals enable row level security;
alter table public.goal_tags enable row level security;
alter table public.tasks enable row level security;
alter table public.task_tags enable row level security;

-- Profiles: Map auth.uid() to profiles.auth_user_id
create policy "Users can view own profile"
  on public.profiles for select
  to authenticated
  using (auth_user_id = (select auth.uid()));

create policy "Users can update own profile"
  on public.profiles for update
  to authenticated
  using (auth_user_id = (select auth.uid()))
  with check (auth_user_id = (select auth.uid()));

create policy "Users can insert own profile"
  on public.profiles for insert
  to authenticated
  with check (auth_user_id = (select auth.uid()));

-- Allowed Members: Admins have full access; authenticated users can check their own email
create policy "Admins have full access to allowed_members"
  on public.allowed_members for all
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.auth_user_id = (select auth.uid())
        and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.auth_user_id = (select auth.uid())
        and profiles.role = 'admin'
    )
  );

create policy "Users can check own email in allowed_members"
  on public.allowed_members for select
  to authenticated
  using (email = (select auth.jwt()->>'email'));

-- User Items
create policy "Users can view own items"
  on public.user_items for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own items"
  on public.user_items for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can update own items"
  on public.user_items for update
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())))
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own items"
  on public.user_items for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Diaries
create policy "Users can view own diaries"
  on public.diaries for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own diaries"
  on public.diaries for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can update own diaries"
  on public.diaries for update
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())))
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own diaries"
  on public.diaries for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Diary Entries
create policy "Users can view own diary entries"
  on public.diary_entries for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own diary entries"
  on public.diary_entries for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can update own diary entries"
  on public.diary_entries for update
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())))
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own diary entries"
  on public.diary_entries for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Tag Categories
create policy "Users can view own tag categories"
  on public.tag_categories for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own tag categories"
  on public.tag_categories for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can update own tag categories"
  on public.tag_categories for update
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())))
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own tag categories"
  on public.tag_categories for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Tags
create policy "Users can view own tags"
  on public.tags for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own tags"
  on public.tags for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can update own tags"
  on public.tags for update
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())) and is_system = false)
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())) and is_system = false);

create policy "Users can delete own tags"
  on public.tags for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())) and is_system = false);

-- Diary Entry Tags Junction
create policy "Users can view own diary entry tags"
  on public.diary_entry_tags for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own diary entry tags"
  on public.diary_entry_tags for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own diary entry tags"
  on public.diary_entry_tags for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Document Tags Junction
create policy "Users can view own document tags"
  on public.document_tags for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own document tags"
  on public.document_tags for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own document tags"
  on public.document_tags for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Goals
create policy "Users can view own goals"
  on public.goals for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own goals"
  on public.goals for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can update own goals"
  on public.goals for update
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())))
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own goals"
  on public.goals for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Goal Tags Junction
create policy "Users can view own goal tags"
  on public.goal_tags for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own goal tags"
  on public.goal_tags for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own goal tags"
  on public.goal_tags for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Tasks
create policy "Users can view own tasks"
  on public.tasks for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own tasks"
  on public.tasks for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can update own tasks"
  on public.tasks for update
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())))
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own tasks"
  on public.tasks for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- Task Tags Junction
create policy "Users can view own task tags"
  on public.task_tags for select
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can insert own task tags"
  on public.task_tags for insert
  to authenticated
  with check (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

create policy "Users can delete own task tags"
  on public.task_tags for delete
  to authenticated
  using (user_id = (select p.id from public.profiles p where p.auth_user_id = (select auth.uid())));

-- ==============================================================================
-- 5. TRIGGERS & PROCEDURES
-- ==============================================================================

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger on_profiles_updated before update on public.profiles for each row execute function public.handle_updated_at();
create trigger on_user_items_updated before update on public.user_items for each row execute function public.handle_updated_at();
create trigger on_diaries_updated before update on public.diaries for each row execute function public.handle_updated_at();
create trigger on_diary_entries_updated before update on public.diary_entries for each row execute function public.handle_updated_at();
create trigger set_goals_updated_at before update on public.goals for each row execute function public.handle_updated_at();
create trigger set_tasks_updated_at before update on public.tasks for each row execute function public.handle_updated_at();
create trigger on_tag_categories_updated before update on public.tag_categories for each row execute function public.handle_updated_at();
create trigger on_tags_updated before update on public.tags for each row execute function public.handle_updated_at();

-- Trigger: create profile on auth signup with integer profile ID
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  is_admin boolean;
  is_whitelisted boolean;
begin
  select exists(select 1 from public.profiles where email = new.email and role = 'admin') into is_admin;
  select exists(select 1 from public.allowed_members where email = new.email and status = 'active') into is_whitelisted;

  insert into public.profiles (
    auth_user_id,
    email,
    full_name,
    avatar_url,
    role
  )
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', ''),
    case when is_admin then 'admin' else 'member' end
  )
  on conflict (auth_user_id) do update set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, profiles.full_name),
    avatar_url = coalesce(excluded.avatar_url, profiles.avatar_url),
    updated_at = now();

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- ==============================================================================
-- 6. RPC PROCEDURES WITH NUMERIC IDENTIFIERS
-- ==============================================================================

-- 6.1 get_diary_stats
create or replace function public.get_diary_stats(
  p_diary_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_total_entries integer := 0;
  v_total_words integer := 0;
  v_avg_energy numeric := 0;
  v_hearted_count integer := 0;
  v_current_streak integer := 0;
  v_longest_streak integer := 0;
  v_mood_breakdown jsonb := '{}'::jsonb;
  v_all_tags text[] := '{}'::text[];
  v_prev_date date;
  v_curr_streak_calc integer := 0;
  v_r record;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  select
    count(*),
    coalesce(sum(word_count), 0),
    coalesce(round(avg(energy_level), 2), 0),
    count(*) filter (where is_hearted = true)
  into
    v_total_entries,
    v_total_words,
    v_avg_energy,
    v_hearted_count
  from public.diary_entries
  where user_id = v_profile_id
    and (p_diary_id is null or diary_id = p_diary_id);

  select jsonb_object_agg(mood, mood_count)
  into v_mood_breakdown
  from (
    select mood, count(*) as mood_count
    from public.diary_entries
    where user_id = v_profile_id
      and (p_diary_id is null or diary_id = p_diary_id)
    group by mood
  ) moods;

  select coalesce(array_agg(distinct tag), '{}'::text[])
  into v_all_tags
  from public.diary_entries,
       unnest(tags) as tag
  where user_id = v_profile_id
    and (p_diary_id is null or diary_id = p_diary_id);

  v_prev_date := null;
  for v_r in (
    select distinct entry_date
    from public.diary_entries
    where user_id = v_profile_id
    order by entry_date desc
  ) loop
    if v_prev_date is null then
      if v_r.entry_date = current_date or v_r.entry_date = current_date - 1 then
        v_curr_streak_calc := 1;
        v_current_streak := 1;
      else
        v_curr_streak_calc := 1;
      end if;
    elsif v_prev_date - v_r.entry_date = 1 then
      v_curr_streak_calc := v_curr_streak_calc + 1;
      if v_current_streak > 0 then
        v_current_streak := v_curr_streak_calc;
      end if;
    else
      v_curr_streak_calc := 1;
    end if;

    if v_curr_streak_calc > v_longest_streak then
      v_longest_streak := v_curr_streak_calc;
    end if;

    v_prev_date := v_r.entry_date;
  end loop;

  return jsonb_build_object(
    'total_entries', v_total_entries,
    'total_words', v_total_words,
    'average_energy', v_avg_energy,
    'hearted_entries', v_hearted_count,
    'current_streak', v_current_streak,
    'longest_streak', v_longest_streak,
    'mood_breakdown', coalesce(v_mood_breakdown, '{}'::jsonb),
    'tags', v_all_tags
  );
end;
$$;

-- 6.2 get_user_diaries_overview
create or replace function public.get_user_diaries_overview()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_result jsonb;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', d.id,
        'name', d.name,
        'description', d.description,
        'theme', d.theme,
        'cover_color', d.cover_color,
        'is_favorite', d.is_favorite,
        'is_archived', d.is_archived,
        'sort_order', d.sort_order,
        'entries_count', coalesce(stats.entries_count, 0),
        'highest_page_number', coalesce(stats.highest_page_number, 0),
        'latest_entry_date', stats.latest_entry_date,
        'created_at', d.created_at,
        'updated_at', d.updated_at
      ) order by d.is_favorite desc, d.sort_order asc, d.created_at desc
    ),
    '[]'::jsonb
  )
  into v_result
  from public.diaries d
  left join lateral (
    select
      count(*)::int as entries_count,
      max(page_number)::int as highest_page_number,
      max(entry_date) as latest_entry_date
    from public.diary_entries e
    where e.diary_id = d.id and e.user_id = v_profile_id
  ) stats on true
  where d.user_id = v_profile_id;

  return v_result;
end;
$$;

-- 6.3 reorder_diaries
create or replace function public.reorder_diaries(
  p_diary_ids bigint[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  i integer;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_diary_ids is null or array_length(p_diary_ids, 1) = 0 then
    return;
  end if;

  for i in 1 .. array_length(p_diary_ids, 1) loop
    update public.diaries
    set sort_order = i,
        updated_at = now()
    where id = p_diary_ids[i]
      and user_id = v_profile_id;
  end loop;
end;
$$;

-- 6.4 create_diary_with_first_page
create or replace function public.create_diary_with_first_page(
  p_name text,
  p_description text default null,
  p_theme text default 'vintage',
  p_cover_color text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_diary_id bigint;
  v_entry_id bigint;
  v_today date := current_date;
  v_date_str text;
  v_day_of_week text;
  v_year_str text;
  v_cover_color text;
  v_result jsonb;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  v_cover_color := coalesce(p_cover_color, case 
    when p_theme = 'vintage' then '#8C3A27'
    when p_theme = 'classic' then '#1E3A5F'
    else '#172330'
  end);

  v_date_str := to_char(v_today, 'FMMonth FMDD');
  v_day_of_week := to_char(v_today, 'FMDay');
  v_year_str := 'Anno ' || to_char(v_today, 'YYYY');

  insert into public.diaries (
    user_id,
    name,
    description,
    theme,
    cover_color,
    is_favorite,
    is_archived
  ) values (
    v_profile_id,
    coalesce(nullif(trim(p_name), ''), 'Untitled Tome'),
    p_description,
    coalesce(p_theme, 'vintage'),
    v_cover_color,
    false,
    false
  )
  returning id into v_diary_id;

  insert into public.diary_entries (
    diary_id,
    user_id,
    page_number,
    entry_date,
    date_str,
    day_of_week,
    year_str,
    title,
    description,
    gratitude,
    energy_level,
    start_time,
    end_time,
    mood,
    weather,
    is_hearted,
    tags
  ) values (
    v_diary_id,
    v_profile_id,
    1,
    v_today,
    v_date_str,
    v_day_of_week,
    v_year_str,
    '',
    '',
    array['', '', '']::text[],
    3,
    '09:00',
    '17:00',
    '🌿 Calm',
    'sunny',
    false,
    array['Fresh Inscription']::text[]
  )
  returning id into v_entry_id;

  select jsonb_build_object(
    'id', d.id,
    'user_id', d.user_id,
    'name', d.name,
    'description', d.description,
    'theme', d.theme,
    'cover_color', d.cover_color,
    'is_favorite', d.is_favorite,
    'is_archived', d.is_archived,
    'sort_order', d.sort_order,
    'entries_count', 1,
    'highest_page_number', 1,
    'latest_entry_date', v_today,
    'created_at', d.created_at,
    'updated_at', d.updated_at,
    'first_entry_id', v_entry_id
  )
  into v_result
  from public.diaries d
  where d.id = v_diary_id;

  return v_result;
end;
$$;

-- 6.5 create_diary_entry
create or replace function public.create_diary_entry(
  p_diary_id bigint,
  p_title text default '',
  p_description text default '',
  p_gratitude text[] default array['', '', '']::text[],
  p_energy_level integer default 3,
  p_start_time text default '09:00',
  p_end_time text default '17:00',
  p_mood text default '🌿 Calm',
  p_weather text default 'sunny',
  p_is_hearted boolean default false,
  p_tags text[] default array['Daily Reflection']::text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_next_page int;
  v_today date := current_date;
  v_date_str text;
  v_day_of_week text;
  v_year_str text;
  v_entry record;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  select coalesce(max(page_number), 0) + 1
  into v_next_page
  from public.diary_entries
  where diary_id = p_diary_id and user_id = v_profile_id;

  v_date_str := to_char(v_today, 'FMMonth FMDD');
  v_day_of_week := to_char(v_today, 'FMDay');
  v_year_str := 'Anno ' || to_char(v_today, 'YYYY');

  insert into public.diary_entries (
    diary_id,
    user_id,
    page_number,
    entry_date,
    date_str,
    day_of_week,
    year_str,
    title,
    description,
    gratitude,
    energy_level,
    start_time,
    end_time,
    mood,
    weather,
    is_hearted,
    tags
  ) values (
    p_diary_id,
    v_profile_id,
    v_next_page,
    v_today,
    v_date_str,
    v_day_of_week,
    v_year_str,
    coalesce(p_title, ''),
    coalesce(p_description, ''),
    coalesce(p_gratitude, array['', '', '']::text[]),
    coalesce(p_energy_level, 3),
    coalesce(p_start_time, '09:00'),
    coalesce(p_end_time, '17:00'),
    coalesce(p_mood, '🌿 Calm'),
    coalesce(p_weather, 'sunny'),
    coalesce(p_is_hearted, false),
    coalesce(p_tags, array['Daily Reflection']::text[])
  )
  returning * into v_entry;

  return to_jsonb(v_entry);
end;
$$;

-- 6.6 provision_feature_tag_categories
create or replace function public.provision_feature_tag_categories(p_feature text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_count int;
  v_cat_id bigint;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then
    return jsonb_build_object('success', false, 'error', 'User not authenticated');
  end if;

  select count(*) into v_count
  from public.tag_categories
  where user_id = v_profile_id and feature = p_feature;

  if v_count = 0 then
    if p_feature = 'diary' then
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'diary', 'Context', '#3B82F6', 1, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;
      
      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'diary' and name = 'Context';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Deep Work', true),
          (v_cat_id, v_profile_id, 'Reflections', true),
          (v_cat_id, v_profile_id, 'Planning', true)
        on conflict (category_id, name) do nothing;
      end if;

      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'diary', 'Energy Level', '#10B981', 2, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'diary' and name = 'Energy Level';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'High Vitality', true),
          (v_cat_id, v_profile_id, 'Medium Vitality', true),
          (v_cat_id, v_profile_id, 'Rest & Recovery', true)
        on conflict (category_id, name) do nothing;
      end if;

    elsif p_feature = 'document' then
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'document', 'Department', '#8B5CF6', 1, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'document' and name = 'Department';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Engineering', true),
          (v_cat_id, v_profile_id, 'Research', true),
          (v_cat_id, v_profile_id, 'Governance', true)
        on conflict (category_id, name) do nothing;
      end if;

      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'document', 'Document Type', '#F59E0B', 2, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'document' and name = 'Document Type';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Report', true),
          (v_cat_id, v_profile_id, 'Charter', true),
          (v_cat_id, v_profile_id, 'Dispatch', true)
        on conflict (category_id, name) do nothing;
      end if;

    elsif p_feature = 'goals' then
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'goals', 'Domain', '#6366F1', 1, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'goals' and name = 'Domain';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Civic & Guild', true),
          (v_cat_id, v_profile_id, 'Knowledge & Craft', true),
          (v_cat_id, v_profile_id, 'Health & Vitality', true),
          (v_cat_id, v_profile_id, 'Finance & Capital', true),
          (v_cat_id, v_profile_id, 'Home & Hearth', true),
          (v_cat_id, v_profile_id, 'Creative & Venture', true)
        on conflict (category_id, name) do nothing;
      end if;

      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'goals', 'Energy & Bandwidth', '#10B981', 2, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'goals' and name = 'Energy & Bandwidth';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Deep Focus', true),
          (v_cat_id, v_profile_id, 'Quick Win', true),
          (v_cat_id, v_profile_id, 'Administrative', true),
          (v_cat_id, v_profile_id, 'Collaborative', true)
        on conflict (category_id, name) do nothing;
      end if;

      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'goals', 'Impact & Leverage', '#F59E0B', 3, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'goals' and name = 'Impact & Leverage';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'High Leverage', true),
          (v_cat_id, v_profile_id, 'Foundational / Enabler', true),
          (v_cat_id, v_profile_id, 'Maintenance', true)
        on conflict (category_id, name) do nothing;
      end if;

      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'goals', 'Horizon & Cycle', '#0EA5E9', 4, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'goals' and name = 'Horizon & Cycle';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Immediate Focus', true),
          (v_cat_id, v_profile_id, 'Quarterly Milestone', true),
          (v_cat_id, v_profile_id, 'Long-term Horizon', true)
        on conflict (category_id, name) do nothing;
      end if;

      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'goals', 'Execution Archetype', '#8B5CF6', 5, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'goals' and name = 'Execution Archetype';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Project Deliverable', true),
          (v_cat_id, v_profile_id, 'Ritual & Habit', true),
          (v_cat_id, v_profile_id, 'Research & Discovery', true)
        on conflict (category_id, name) do nothing;
      end if;

    elsif p_feature = 'tasks' then
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'tasks', 'Life Area', '#6366F1', 1, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'tasks' and name = 'Life Area';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Projects', true),
          (v_cat_id, v_profile_id, 'Chores', true),
          (v_cat_id, v_profile_id, 'Market & Shopping', true),
          (v_cat_id, v_profile_id, 'Personal Care', true),
          (v_cat_id, v_profile_id, 'Finance & Bills', true)
        on conflict (category_id, name) do nothing;
      end if;

      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'tasks', 'Effort & Pace', '#10B981', 2, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'tasks' and name = 'Effort & Pace';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Quick (<15m)', true),
          (v_cat_id, v_profile_id, 'Deep Focus', true),
          (v_cat_id, v_profile_id, 'Routine / Habit', true)
        on conflict (category_id, name) do nothing;
      end if;

      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_profile_id, 'tasks', 'Context / Location', '#0EA5E9', 3, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is null then
        select id into v_cat_id from public.tag_categories where user_id = v_profile_id and feature = 'tasks' and name = 'Context / Location';
      end if;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name, is_system)
        values 
          (v_cat_id, v_profile_id, 'Home', true),
          (v_cat_id, v_profile_id, 'Work & Desk', true),
          (v_cat_id, v_profile_id, 'Out & Errands', true),
          (v_cat_id, v_profile_id, 'Online / Calls', true)
        on conflict (category_id, name) do nothing;
      end if;
    end if;

    return jsonb_build_object('success', true, 'provisioned', true, 'feature', p_feature);
  end if;

  return jsonb_build_object('success', true, 'provisioned', false, 'feature', p_feature);
end;
$$;

-- 6.7 get_citizen_passport_metrics
create or replace function public.get_citizen_passport_metrics()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_profile record;
  v_total_items int;
  v_pinned_items int;
  v_favorite_items int;
  v_residence text;
  v_clearance_title text;
  v_streak int;
  v_stamps jsonb;
  v_passport_number text;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  select * into v_profile
  from public.profiles
  where id = v_profile_id;

  if not found then
    raise exception 'Citizen profile not found';
  end if;

  select
    count(*),
    count(*) filter (where is_pinned = true),
    count(*) filter (where is_favorite = true)
  into
    v_total_items,
    v_pinned_items,
    v_favorite_items
  from public.user_items
  where user_id = v_profile_id;

  v_residence := coalesce(v_profile.metadata->>'residence', 'Archival Broadside');
  v_clearance_title := coalesce(v_profile.metadata->>'clearance_title', case when v_profile.role = 'admin' then 'Grand Chancellor' else 'Level II Scribe' end);
  v_streak := coalesce((v_profile.metadata->>'ritual_streak_days')::int, 0);
  v_stamps := coalesce(v_profile.metadata->'unlocked_stamps', jsonb_build_array('founding_scribe'));
  v_passport_number := 'CC-' || lpad(v_profile_id::text, 6, '0');

  return jsonb_build_object(
    'id', v_profile.id,
    'user_id', v_profile.id,
    'email', v_profile.email,
    'full_name', v_profile.full_name,
    'username', v_profile.username,
    'avatar_url', v_profile.avatar_url,
    'bio', v_profile.bio,
    'role', v_profile.role,
    'passport_number', v_passport_number,
    'residence', v_residence,
    'clearance_title', v_clearance_title,
    'ritual_streak_days', v_streak,
    'unlocked_stamps', v_stamps,
    'total_items', coalesce(v_total_items, 0),
    'pinned_items', coalesce(v_pinned_items, 0),
    'favorite_items', coalesce(v_favorite_items, 0),
    'created_at', v_profile.created_at,
    'updated_at', v_profile.updated_at
  );
end;
$$;

-- 6.8 update_citizen_passport
create or replace function public.update_citizen_passport(
  p_full_name text default null,
  p_username text default null,
  p_bio text default null,
  p_avatar_url text default null,
  p_metadata jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id bigint;
  v_updated_profile record;
  v_current_metadata jsonb;
  v_new_username text;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();
  if v_profile_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_username is not null then
    v_new_username := lower(trim(regexp_replace(p_username, '[^a-zA-Z0-9_]', '', 'g')));
    if length(v_new_username) < 3 then
      raise exception 'Username must be at least 3 characters';
    end if;

    if exists (
      select 1 from public.profiles
      where username = v_new_username and id != v_profile_id
    ) then
      raise exception 'Username is already taken';
    end if;
  end if;

  select metadata into v_current_metadata from public.profiles where id = v_profile_id;
  if p_metadata is not null then
    v_current_metadata := coalesce(v_current_metadata, '{}'::jsonb) || p_metadata;
  end if;

  update public.profiles
  set
    full_name = coalesce(trim(p_full_name), full_name),
    username = coalesce(v_new_username, username),
    bio = coalesce(trim(p_bio), bio),
    avatar_url = coalesce(trim(p_avatar_url), avatar_url),
    metadata = coalesce(v_current_metadata, metadata),
    updated_at = now()
  where id = v_profile_id
  returning * into v_updated_profile;

  return to_jsonb(v_updated_profile);
end;
$$;

-- 6.9 Grants
grant execute on function public.get_diary_stats(bigint) to authenticated;
grant execute on function public.get_user_diaries_overview() to authenticated;
grant execute on function public.reorder_diaries(bigint[]) to authenticated;
grant execute on function public.create_diary_with_first_page(text, text, text, text) to authenticated;
grant execute on function public.create_diary_entry(bigint, text, text, text[], integer, text, text, text, text, boolean, text[]) to authenticated;
grant execute on function public.provision_feature_tag_categories(text) to authenticated;
grant execute on function public.get_citizen_passport_metrics() to authenticated;
grant execute on function public.update_citizen_passport(text, text, text, text, jsonb) to authenticated;
