-- Migration: 20260920000000_document_tags_schema.sql
-- Universal Document & Entity Tagging System Schema
-- Adds tag_categories (BIGINT id), tags (BIGINT id), diary_entry_tags, document_tags, indexes, triggers, and RLS

-- ==============================================================================
-- 1. TABLES
-- ==============================================================================

-- 1.1 Tag Categories Table (Numeric Identity)
create table if not exists public.tag_categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  feature text not null default 'general',
  name text not null,
  color text not null default '#6B7280',
  display_order integer not null default 0,
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint uq_user_feature_category_name unique (user_id, feature, name)
);

-- 1.2 Tags Table (Numeric Identity)
create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.tag_categories(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  color text default null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint uq_user_tag_in_category unique (category_id, name)
);

-- 1.3 Diary Entry Tags Junction Table
create table if not exists public.diary_entry_tags (
  entry_id uuid not null references public.diary_entries(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),

  primary key (entry_id, tag_id)
);

-- 1.4 Document Tags Junction Table
create table if not exists public.document_tags (
  document_id uuid not null,
  tag_id bigint not null references public.tags(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),

  primary key (document_id, tag_id)
);

-- Comments
comment on table public.tag_categories is 'Top-level semantic dimensions (e.g. Context, Energy Level, Department) optionally scoped by feature.';
comment on table public.tags is 'Individual metadata labels belonging to a specific tag category.';
comment on table public.diary_entry_tags is 'Junction table associating numeric tags with user diary entries.';
comment on table public.document_tags is 'Junction table associating numeric tags with user documents.';

-- ==============================================================================
-- 2. TRIGGERS (Updated At)
-- ==============================================================================

drop trigger if exists on_tag_categories_updated on public.tag_categories;
create trigger on_tag_categories_updated
  before update on public.tag_categories
  for each row
  execute function public.handle_updated_at();

drop trigger if exists on_tags_updated on public.tags;
create trigger on_tags_updated
  before update on public.tags
  for each row
  execute function public.handle_updated_at();

-- ==============================================================================
-- 3. PERFORMANCE INDEXES
-- ==============================================================================

create index if not exists idx_tag_categories_user_feature 
  on public.tag_categories(user_id, feature, display_order asc, name asc);

create index if not exists idx_tags_category_id 
  on public.tags(category_id);

create index if not exists idx_tags_user_id 
  on public.tags(user_id, name asc);

create index if not exists idx_diary_entry_tags_tag_id 
  on public.diary_entry_tags(tag_id, user_id);

create index if not exists idx_diary_entry_tags_entry_id 
  on public.diary_entry_tags(entry_id, user_id);

create index if not exists idx_document_tags_tag_id 
  on public.document_tags(tag_id, user_id);

create index if not exists idx_document_tags_document_id 
  on public.document_tags(document_id, user_id);

-- ==============================================================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ==============================================================================

alter table public.tag_categories enable row level security;
alter table public.tags enable row level security;
alter table public.diary_entry_tags enable row level security;
alter table public.document_tags enable row level security;

-- Drop existing policies if any
drop policy if exists "Users can view own tag categories" on public.tag_categories;
drop policy if exists "Users can insert own tag categories" on public.tag_categories;
drop policy if exists "Users can update own tag categories" on public.tag_categories;
drop policy if exists "Users can delete own tag categories" on public.tag_categories;

drop policy if exists "Users can view own tags" on public.tags;
drop policy if exists "Users can insert own tags" on public.tags;
drop policy if exists "Users can update own tags" on public.tags;
drop policy if exists "Users can delete own tags" on public.tags;

drop policy if exists "Users can view own diary entry tags" on public.diary_entry_tags;
drop policy if exists "Users can insert own diary entry tags" on public.diary_entry_tags;
drop policy if exists "Users can delete own diary entry tags" on public.diary_entry_tags;

drop policy if exists "Users can view own document tags" on public.document_tags;
drop policy if exists "Users can insert own document tags" on public.document_tags;
drop policy if exists "Users can delete own document tags" on public.document_tags;

-- Tag Categories Policies
create policy "Users can view own tag categories"
  on public.tag_categories for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert own tag categories"
  on public.tag_categories for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update own tag categories"
  on public.tag_categories for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete own tag categories"
  on public.tag_categories for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Tags Policies
create policy "Users can view own tags"
  on public.tags for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert own tags"
  on public.tags for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update own tags"
  on public.tags for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete own tags"
  on public.tags for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Diary Entry Tags Junction Policies
create policy "Users can view own diary entry tags"
  on public.diary_entry_tags for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert own diary entry tags"
  on public.diary_entry_tags for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can delete own diary entry tags"
  on public.diary_entry_tags for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Document Tags Junction Policies
create policy "Users can view own document tags"
  on public.document_tags for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert own document tags"
  on public.document_tags for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can delete own document tags"
  on public.document_tags for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- ==============================================================================
-- 5. RPC: ON-DEMAND FEATURE TAG PROVISIONING
-- ==============================================================================

create or replace function public.provision_feature_tag_categories(p_feature text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_cat_id bigint;
  v_count int;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  -- Check if user already has categories for this feature
  select count(*) into v_count
  from public.tag_categories
  where user_id = v_user_id and feature = p_feature;

  if v_count = 0 then
    if p_feature = 'diary' then
      -- Context category
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_user_id, 'diary', 'Context', '#3B82F6', 1, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;
      
      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name)
        values 
          (v_cat_id, v_user_id, 'Deep Work'),
          (v_cat_id, v_user_id, 'Reflections'),
          (v_cat_id, v_user_id, 'Planning')
        on conflict (category_id, name) do nothing;
      end if;

      -- Energy Level category
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_user_id, 'diary', 'Energy Level', '#10B981', 2, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name)
        values 
          (v_cat_id, v_user_id, 'High Vitality'),
          (v_cat_id, v_user_id, 'Medium Vitality'),
          (v_cat_id, v_user_id, 'Rest & Recovery')
        on conflict (category_id, name) do nothing;
      end if;

    elsif p_feature = 'document' then
      -- Department category
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_user_id, 'document', 'Department', '#8B5CF6', 1, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name)
        values 
          (v_cat_id, v_user_id, 'Engineering'),
          (v_cat_id, v_user_id, 'Research'),
          (v_cat_id, v_user_id, 'Governance')
        on conflict (category_id, name) do nothing;
      end if;

      -- Document Type category
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_user_id, 'document', 'Document Type', '#F59E0B', 2, true)
      on conflict (user_id, feature, name) do nothing
      returning id into v_cat_id;

      if v_cat_id is not null then
        insert into public.tags (category_id, user_id, name)
        values 
          (v_cat_id, v_user_id, 'Report'),
          (v_cat_id, v_user_id, 'Charter'),
          (v_cat_id, v_user_id, 'Dispatch')
        on conflict (category_id, name) do nothing;
      end if;
    else
      -- Default custom category for other features
      insert into public.tag_categories (user_id, feature, name, color, display_order, is_system)
      values (v_user_id, p_feature, 'General', '#6B7280', 1, false)
      on conflict (user_id, feature, name) do nothing;
    end if;
  end if;

  return jsonb_build_object(
    'success', true,
    'feature', p_feature,
    'provisioned', (v_count = 0)
  );
end;
$$;
