-- Migration: 20260930000000_migrate_tasks_id_to_bigint.sql
-- Migration to alter/recreate tasks table with numeric ID (bigint generated by default as identity)
-- Supports numeric task IDs, parent_id numeric foreign keys, and task_tags integration.

-- 1. Drop dependent tables or objects if needed
drop table if exists public.task_tags cascade;
drop table if exists public.tasks cascade;

-- 2. Create Tasks Table with Numeric ID
create table public.tasks (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    parent_id bigint references public.tasks(id) on delete cascade,
    
    -- Content
    title varchar(255) not null,
    description text,
    status public.task_status not null default 'todo',
    priority public.task_priority not null default 'normal',
    
    -- Scheduling & Execution
    scheduled_date date,
    due_date timestamptz,
    completed_at timestamptz,
    
    time_estimate_minutes integer check (time_estimate_minutes is null or time_estimate_minutes >= 0),
    actual_minutes integer check (actual_minutes is null or actual_minutes >= 0),
    sort_order integer not null default 0,
    
    -- Auditing
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 3. Task Tags Junction Table (Numeric Task ID + Numeric Tag ID)
create table public.task_tags (
    task_id bigint not null references public.tasks(id) on delete cascade,
    tag_id bigint not null references public.tags(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    created_at timestamptz not null default now(),

    primary key (task_id, tag_id)
);

-- Comments
comment on table public.tasks is 'Day-to-day actionable task ledger with numeric identity.';
comment on table public.task_tags is 'Junction table associating universal tags with numeric task IDs.';

-- 4. Triggers (Updated At)
drop trigger if exists set_tasks_updated_at on public.tasks;
create trigger set_tasks_updated_at
    before update on public.tasks
    for each row
    execute function public.handle_updated_at();

-- 5. Performance Indexes (Following Postgres Best Practices)
create index if not exists idx_tasks_user_id on public.tasks(user_id);
create index if not exists idx_tasks_parent_id on public.tasks(parent_id);
create index if not exists idx_tasks_user_scheduled on public.tasks(user_id, scheduled_date);
create index if not exists idx_tasks_user_status on public.tasks(user_id, status);
create index if not exists idx_tasks_user_priority on public.tasks(user_id, priority);
create index if not exists idx_tasks_created_at on public.tasks(user_id, created_at desc);

create index if not exists idx_task_tags_tag_id on public.task_tags(tag_id, user_id);
create index if not exists idx_task_tags_user_id on public.task_tags(user_id);

-- 6. Row Level Security (RLS)
alter table public.tasks enable row level security;
alter table public.task_tags enable row level security;

-- Tasks Policies (Strict Tenant Isolation with auth.uid() wrapped in SELECT for subquery optimization)
create policy "Users can view own tasks"
    on public.tasks for select
    to authenticated
    using ((select auth.uid()) = user_id);

create policy "Users can insert own tasks"
    on public.tasks for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

create policy "Users can update own tasks"
    on public.tasks for update
    to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

create policy "Users can delete own tasks"
    on public.tasks for delete
    to authenticated
    using ((select auth.uid()) = user_id);

-- Task Tags Junction Policies
create policy "Users can view own task tags"
    on public.task_tags for select
    to authenticated
    using ((select auth.uid()) = user_id);

create policy "Users can insert own task tags"
    on public.task_tags for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

create policy "Users can delete own task tags"
    on public.task_tags for delete
    to authenticated
    using ((select auth.uid()) = user_id);
