-- Migration: 20261005000002_create_locations_schema.sql
-- Description: Universal reusable hierarchical locations table with RLS and indexes

create table if not exists public.locations (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.profiles(id) on delete cascade,
    parent_id bigint references public.locations(id) on delete cascade,
    name text not null,
    description text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Comments
comment on table public.locations is 'Universal hierarchical location tree (e.g. rooms, zones, cabinets, bins, slots) reusable across any feature.';
comment on column public.locations.parent_id is 'Self-referencing foreign key for nested spatial hierarchy.';

-- Indexes
create index if not exists idx_locations_user_id on public.locations(user_id);
create index if not exists idx_locations_parent_id on public.locations(parent_id);

-- Enable Row Level Security
alter table public.locations enable row level security;

-- RLS Policies
create policy "Users can view their own locations"
    on public.locations
    for select
    using (user_id = (select id from public.profiles where auth_user_id = auth.uid()));

create policy "Users can insert their own locations"
    on public.locations
    for insert
    with check (user_id = (select id from public.profiles where auth_user_id = auth.uid()));

create policy "Users can update their own locations"
    on public.locations
    for update
    using (user_id = (select id from public.profiles where auth_user_id = auth.uid()))
    with check (user_id = (select id from public.profiles where auth_user_id = auth.uid()));

create policy "Users can delete their own locations"
    on public.locations
    for delete
    using (user_id = (select id from public.profiles where auth_user_id = auth.uid()));
