-- ==============================================================================
-- Migration: 20261005000003_create_user_items_schema.sql
-- Description: HomeOps user_items schema (Consumables & Assets Ledger)
-- ==============================================================================

-- 1. Create table (drop obsolete legacy stub table if it exists)
drop table if exists public.user_items cascade;

create table public.user_items (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.profiles(id) on delete cascade,
    name text not null,
    description text,
    item_type text not null check (item_type in ('consumable', 'asset')),
    
    -- Taxonomy & Location references
    category_id bigint references public.tag_categories(id) on delete set null,
    tag_ids bigint[] not null default '{}',
    location_id bigint references public.locations(id) on delete set null,

    -- Consumable Fields
    quantity numeric default 1 check (quantity >= 0),
    unit_of_measure text default 'pcs',          -- 'pcs', 'kg', 'g', 'l', 'ml', 'box'
    reorder_threshold numeric check (reorder_threshold >= 0),
    expiration_date date,
    
    -- Asset & Custody Fields
    condition_status text check (
        condition_status is null or 
        condition_status in ('new', 'good', 'fair', 'damaged', 'maintenance', 'retired')
    ),
    is_loaned boolean default false not null,
    loaned_to text,                              -- Borrower contact or name
    loaned_at timestamptz,
    
    -- Flexible metadata (serials, warranties, specs, purchase cost)
    metadata jsonb default '{}'::jsonb not null,
    
    -- Lifecycle
    is_archived boolean default false not null,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null,

    -- Data integrity constraint
    constraint check_consumable_fields check (
        item_type != 'consumable' or (condition_status is null and is_loaned = false)
    )
);

-- Comments
comment on table public.user_items is 'HomeOps inventory tracking consumable supplies and durable tracked assets.';
comment on column public.user_items.tag_ids is 'Array of tag IDs associated with this item for faceted filtering.';
comment on column public.user_items.location_id is 'Reference to public.locations hierarchy.';

-- 2. Targeted Query Indexes
create index if not exists idx_user_items_user_id 
    on public.user_items(user_id);

create index if not exists idx_user_items_location_id 
    on public.user_items(location_id);

create index if not exists idx_user_items_category_id 
    on public.user_items(category_id);

create index if not exists idx_user_items_user_type 
    on public.user_items(user_id, item_type) 
    where not is_archived;

create index if not exists idx_user_items_reorder 
    on public.user_items(user_id, quantity, reorder_threshold) 
    where item_type = 'consumable' and not is_archived;

create index if not exists idx_user_items_expiring 
    on public.user_items(user_id, expiration_date) 
    where item_type = 'consumable' and expiration_date is not null and not is_archived;

create index if not exists idx_user_items_tag_ids 
    on public.user_items using gin (tag_ids);

create index if not exists idx_user_items_metadata 
    on public.user_items using gin (metadata);

-- 3. Row Level Security (RLS)
alter table public.user_items enable row level security;

create policy "Users can view their own items"
    on public.user_items
    for select
    using (user_id = (select id from public.profiles where auth_user_id = auth.uid()));

create policy "Users can insert their own items"
    on public.user_items
    for insert
    with check (user_id = (select id from public.profiles where auth_user_id = auth.uid()));

create policy "Users can update their own items"
    on public.user_items
    for update
    using (user_id = (select id from public.profiles where auth_user_id = auth.uid()))
    with check (user_id = (select id from public.profiles where auth_user_id = auth.uid()));

create policy "Users can delete their own items"
    on public.user_items
    for delete
    using (user_id = (select id from public.profiles where auth_user_id = auth.uid()));

-- 4. Auto-update Trigger for updated_at
create or replace function public.handle_user_items_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create or replace trigger trg_user_items_updated_at
    before update on public.user_items
    for each row
    execute function public.handle_user_items_updated_at();
