-- ==============================================================================
-- Migration: 20261005000004_create_tag_groups_schema.sql
-- Description: Create tag_groups table and link to tag_categories via group_id.
--              Includes schema_blueprint JSONB on both tag_groups and
--              tag_categories for dynamic, typed, searchable, and filterable
--              item metadata traits.
-- ==============================================================================

-- 1. Create tag_groups table
create table if not exists public.tag_groups (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.profiles(id) on delete cascade,
  feature text not null default 'general',
  name text not null,
  icon text not null default 'folder',
  color text not null default '#6B7280',
  display_order integer not null default 0,
  is_system boolean not null default false,
  schema_blueprint jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint uq_user_feature_tag_group_name unique (user_id, feature, name)
);

-- Comments
comment on table public.tag_groups is 'Top-level semantic domains/clusters (e.g. Food & Kitchen, Household & Cleaning, Personal Care) that group tag categories.';
comment on column public.tag_groups.icon is 'Lucide icon identifier (e.g. utensils, sparkles, heart-pulse, wrench, cpu, archive, compass, check-square).';
comment on column public.tag_groups.schema_blueprint is 'List of dynamic attribute field definitions (key, label, type, unit, filterable, sortable) inherited by categories.';

-- 2. Add group_id and schema_blueprint to tag_categories if they do not exist
do $$
begin
  if not exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' 
      and table_name = 'tag_categories' 
      and column_name = 'group_id'
  ) then
    alter table public.tag_categories 
    add column group_id bigint references public.tag_groups(id) on delete set null;
  end if;

  if not exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' 
      and table_name = 'tag_categories' 
      and column_name = 'schema_blueprint'
  ) then
    alter table public.tag_categories 
    add column schema_blueprint jsonb not null default '[]'::jsonb;
  end if;
end $$;

comment on column public.tag_categories.schema_blueprint is 'Category-specific overrides or additions to dynamic attribute field definitions.';

-- 3. Indexes
create index if not exists idx_tag_groups_user_feature on public.tag_groups(user_id, feature);
create index if not exists idx_tag_categories_group_id on public.tag_categories(group_id);
create index if not exists idx_tag_groups_blueprint on public.tag_groups using gin (schema_blueprint);
create index if not exists idx_tag_categories_blueprint on public.tag_categories using gin (schema_blueprint);

-- 4. Enable RLS
alter table public.tag_groups enable row level security;

-- 5. RLS Policies for tag_groups
create policy "Users can view their own tag groups"
  on public.tag_groups for select
  to authenticated
  using (user_id = (select id from public.profiles where auth_user_id = (select auth.uid())));

create policy "Users can insert their own tag groups"
  on public.tag_groups for insert
  to authenticated
  with check (user_id = (select id from public.profiles where auth_user_id = (select auth.uid())));

-- UPDATE requires USING and WITH CHECK to prevent ownership tampering
create policy "Users can update their own tag groups"
  on public.tag_groups for update
  to authenticated
  using (user_id = (select id from public.profiles where auth_user_id = (select auth.uid())))
  with check (user_id = (select id from public.profiles where auth_user_id = (select auth.uid())));

create policy "Users can delete their own tag groups"
  on public.tag_groups for delete
  to authenticated
  using (user_id = (select id from public.profiles where auth_user_id = (select auth.uid())));

-- 6. Trigger for updated_at on tag_groups
create or replace function public.touch_tag_group_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_tag_groups_updated_at
  before update on public.tag_groups
  for each row
  execute function public.touch_tag_group_updated_at();
